logging:
  level:
    root: DEBUG
    '[com.upstock.client]': DEBUG

server:
  port: 8087

upstock:
  auth:
    url: https://api.upstox.com/v2/login/authorization/token
    redirection_uri: http://localhost:8080/api/login/saveAccessCode
    client_id: 68bcff7a-3856-4f0f-8496-51bee90e0a36
    client_secret: 81jq429l7i
    grant_type: authorization_code
    mockFlag: false

  code:
    value: code
    url: https://api.upstox.com/v2/login/authorization/dialog
    redirection_uri: http://localhost:8080/api/login/saveAccessCode
    client_id: 68bcff7a-3856-4f0f-8496-51bee90e0a36

spring:
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379